//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SkladisteVeleprodaje.rc
//
#define IDB_IZMIJENI_ARTIKL             1
#define IDOK2                           2
#define IDB_IZMIJENI_KLIJENTA           3
#define IDB_IZBRISI_ARTIKL              4
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_SkladisteVeleprodajeTYPE    130
#define IDS_STRING_ID                   200
#define IDS_STRING_NAZIV_ARTIKLA        201
#define IDS_STRING_JEDINICA             202
#define IDS_STRING_STANJE               203
#define IDS_STRING_CIJENA               204
#define IDS_STRING_SIFRA                205
#define IDS_STRING_KLIJENT_ID           206
#define IDS_STRING_NAZIV_KLIJENTA       207
#define IDS_STRING_OIB                  208
#define IDS_STRING_ADRESA               209
#define IDS_STRING_TELEFON              210
#define IDS_STRING_DATUM                211
#define IDS_STRING_ODABERI_KLIJENTA     212
#define IDS_STRING_OBAVEZAN_UNOS_ARTIKLA 213
#define IDS_STRING_OBAVEZAN_UNOS_KLIJENTA 214
#define IDS_STRING_NAZIV                215
#define IDS_STRING_KOLICINA             216
#define IDS_STRING_FAKTURNA             217
#define IDS_STRING_PRODAJNA             218
#define IDS_STRING_RABAT                219
#define IDS_STRING_NABAVNA              220
#define IDS_STRING_OBAVEZAN_UNOS_PODATAKA 221
#define IDS_STRING_SIFRA_POSTOJI        222
#define IDS_STRING_SIFRA_PRAZNA         223
#define IDS_STRING_BROJ_RACUNA          224
#define IDS_STRING_OBAVEZAN_ODABIR_PRIMKE 225
#define IDS_STRING_BROJ_PRIMKE			 226
#define IDD_PODACI_O_KLIJENTIMA_NOVI_PODATAK 311
#define IDD_PODACI_O_ARTIKLIMA_NOVI_PODATAK 313
#define IDD_PODACI_O_ARTIKLIMA_PREGLED  314
#define IDD_PODACI_O_ARTIKLIMA_ARTIKLI  315
#define IDD_PODACI_O_ARTIKLIMA_SVI_ARTIKLI 316
#define IDD_DIALOG1                     317
#define IDD_PODACI_O_KLIJENTIMA_SVI_KLIJENTI 318
#define IDD_PODACI_O_PRIMKAMA_SVE_PRIMKE 319
#define IDD_PODACI_O_PRIMKAMA_NOVI_PODATAK 320
#define IDD_DIALOG2                     321
#define IDD_STAVKE_NOVI_PODATAK         322
#define IDD_DIALOG3                     323
#define IDD_PODACI_O_KLIJENTIMA_ODABERI_KLIJENTA 324
#define IDD_DIALOG4                     325
#define IDD_PODACI_O_ARTIKLIMA_ODABERI_ARTIKL 326
#define IDD_PODACI_O_KLIJENTIMA_UREDI_KLIJENTA 333
#define IDD_DIALOG5                     335
#define IDD_PODACI_O_ARTIKLIMA_UREDI_ARTIKL 335
#define IDD_PODACI_O_PRIMKAMA_UREDI_PODATAK 337
#define IDC_EDIT_SIFRA_ARTIKLA          1000
#define IDC_EDIT_NAZIV_KLIJENTA         1001
#define IDC_EDIT_OIB                    1002
#define IDC_EDIT_ADRESA                 1003
#define IDC_EDIT_TELEFON                1004
#define IDC_EDIT_NAZIV_ARTIKLA          1006
#define IDC_EDIT_MJERA                  1007
#define IDC_EDIT_CIJENA_VP              1008
#define IDC_EDIT_KLIJENT_ID             1009
#define IDC_LIST1                       1012
#define IDB_DODAJ_NOVI_ARTIKL           1014
#define IDB_SPREMI                      1015
#define IDB_DODAJ_NOVOG_KLIJENTA        1016
#define IDB_DODAJ_NOVU_PRIMKU           1017
#define IDB_UREDI_PRIMKU                1018
#define IDC_EDIT_BROJ_PRIMKE            1019
#define IDC_EDIT_ARTIKL_SIFRA           1020
#define IDC_EDIT_DATUM                  1021
#define IDC_EDIT_KOLICINA               1022
#define IDC_EDIT_KLIJENT                1023
#define IDC_EDIT_FAKTURNA_CIJENA        1024
#define IDC_BUTTON1                     1025
#define IDB_DODAJ_NOVI                  1026
#define IDC_BUTTON3                     1027
#define IDC_BUTTON2                     1028
#define IDC_EDIT_RABAT                  1029
#define IDC_BUTTON4                     1030
#define IDC_EDIT_NABAVNA_CIJENA         1031
#define IDC_EDIT_VPC                    1032
#define IDB_ODABERI                     1033
#define IDC_STATIC_ARTIKL_OPIS          1034
#define IDC_BUTTON                      1035
#define IDC_BUTTON_UREDI_KLIJENTA       1036
#define IDB_DODAJ                       1036
#define IDC_EDIT1                       1037
#define IDC_EDIT_SIFRA                  1038
#define IDC_EDIT6                       1039
#define IDC_EDIT2                       1040
#define IDC_EDIT3                       1041
#define IDC_EDIT4                       1042
#define IDB_DODAJ_NOVI_ARTIKL2          1043
#define IDB_UREDI_ARTIKL                1044
#define IDB_OTVORI_PRIMKU               1050
#define IDB_DODAJ_NOVU_PRIMKU2          1051
#define IDC_EDIT_DATUM_PRIMKE           1052
#define IDC_EDIT_BROJ_RACUNA            1053
#define ID_ARTIKLI_NOVIARTIKL           32771
#define ID_ARTIKLI_ARTIKLI              32772
#define ID_KLIJENTI_NOVIKLIJENT         32773
#define ID_KLIJENTI_KLIJENTI            32774
#define ID_PRIMKE_NOVAPRIMKA            32775
#define ID_PRIMKE_PRIMKE                32776
#define ID_HELP_ABOUTSKLADISTEVELEPRODAJE 32777
#define ID_POMO32778                    32778
#define ID_PROBNAPORUKA                 32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        339
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1037
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
